### PR TITLE
Add Keyboard Shortcut Support to Preferences to Toggle Noise Mode

### PR DESCRIPTION
**Pull request by nehayward**
Add keyboard shortcut to support to NoiseBuddy 

## Added 

- Add HotKey Dependency
- Add Keyboard Support to Preference Screen
- Add Codable User Defaults
- Bumped Version to 1.1

## Other

I had to disable "Library Validation" to build NoiseBuddy, I didn't commit this change though.

68969967-42f6ab80-07f7-11ea-8d31-3c7989c68aa8

I'm open to any and all changes so just let me know what you think. Love the app great work @insidegu !

### CODE REVIEW

**Comment by BoD** [comment]
@insidegui Any plans on merging this?  I'm eager to have the ability to quickly switch between noise modes (and am not enough XCode savvy to build this myself 😛 )

**Comment by insidegui** [comment]
I haven't had time to verify this yet since I'm on vacation, I'll check it out next week 😉

**Comment by nehayward** [comment]
I'm happy to help or change anything you want @insidegui

**Comment by RyanBeckett** [comment]
This would be a really useful feature!

**Comment by insidegui** [comment]
Good job, @nehayward !

**Comment by BoD** [comment]
I'm very sorry to ask this here, since I don't know anywhere else to ask (you can't open tickets on this project).  Could there be any way to, in a single shortcut, pause music + disable noise cancelling  /  resume music + enable noise cancelling.

Basically I'm listening to music, I'm in my zone, somebody talks to me - I need to quickly stop the sound AND the noise cancelling.

That would be a killer feature!

**Pull request merged**
