### PR TITLE
Update fishhook to fix startup crash

### PR DESCRIPTION
**Pull request by effektsvk**
Hey, I updated `fishhook.c` file from [fishhook repo](https://github.com/facebook/fishhook) because the app was crashing after startup. I have macOS Monterey 12.1. Here's the crash:
image

### CODE REVIEW

**Comment by insidegui** [comment]
Thanks @effektsvk!

Does the app work at all on macOS Monterey? Sorry, I haven’t had the time to work on porting it, but I had a lot of trouble getting listening mode changing to work in AirBuddy for Monterey, so I suspect there’s more stuff to be done in order for NoiseBuddy to work properly in that version.

**Comment by effektsvk** [comment]
No problem! 😊
It's working okay, I noticed that sometimes the Touch Bar icon is not shown because Music icon overrides it, but specifically switching between transparency and noise cancellation works flawlessly.

**Comment by effektsvk** [comment]
@insidegui Hey, are you planning on merging it? 😅 I don't mind, just asking. 🙂

**Comment by insidegui** [comment]
I was on my holiday break 😄

Just tested this, but unfortunately it doesn't seem to work on my M1 Mac mini running macOS Monterey 12.1 (21C52).

I'm seeing the exact same problem that I was seeing before, where in `NCAVListeningModeController`, `self.context` is `nil`, which to me indicates that the AVF hooking has failed.

Any ideas as to why this would be working for you but not for me?

Screen Shot 2022-01-10 at 10 23 31

**Comment by effektsvk** [comment]
Oh, sorry, I didn't mean to bother you 😅 I'm not really sure why, I'm running the same macOS build. Just checked and it works for me. I forgot to point out in OP that I have Intel MacBook Pro (16-inch 2019). I'm running Xcode 13.1.

image

**Comment by insidegui** [comment]
Interesting. I'm guessing this is probably something about fishhook that's broken for Apple Silicon Macs. I don't have an Intel Mac running Monterey to test, so I'll merge this for now.

I will probably end up porting the same technique I used in AirBuddy once I've shipped its new update, since it doesn't require the hook.

**Comment by mamkos** [comment]
I cant seem to open the application at all on Montery, I have a 2016 Macbook Pro running 12.3.1, any reason why this could be? Also is this the right place to ask stuff like this, im new to GitHub 😅

**Comment by effektsvk** [comment]
Hey @mamkos, generally you should ask in Issues, but this repo doesn't have them, so it's okay, I guess. You can checkout this repository and build it yourself, it should work. This PR contains the fix for the crash but it's only in source code, it was not released yet as a new version.

If you are comfortable with it, I can send you my own build that works and is signed by me.

**Comment by mamkos** [comment]
@effektsvk, how would I go about building it, im quite new to stuff like this? If you would like we could exchange some form of details to discuss elsewhere?

**Comment by effektsvk** [comment]
@mamkos, you can send me an iMessage to my email address (erik.slovak7@gmail.com) and we can chat there :)

**Pull request merged**
